config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :daily_log, only: [:new, :create]
  get "daily_log/report", to: "daily_log#report"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_log.rb
class DailyLog < ApplicationRecord
  validates :log_date, presence: true
  validates :log_date, :uniqueness => {:scope => :user_id}
  validates :values, presence: true
  validate  :values_is_array
  validate  :max_four_values
  validate  :all_values_are_integers

  belongs_to :user

  serialize :values

  def add(value)
    values << value
  end

  def values_is_array
    unless values.is_a?(Array)
      errors[:values] << "Values must be able to take multiple values"
    end
  end

  def max_four_values
    unless values.is_a?(Array) && values.length < 5
      errors[:values] << "Cannot have more than 4 values per day"
    end
  end

  def all_values_are_integers
    if values.is_a?(Array)
      values.each do |value|
        unless value.is_a?(Integer)
          errors[:values] << "#{value} is not an integer"
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :daily_log

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/daily_log_controller.rb
class DailyLogController < ApplicationController
  before_action :authenticate_user!

  def report
    if params[:date]
      # Get date if given in params directly
      @date = Date.strptime(params[:date], "%m-%d-%Y") rescue nil
    elsif params[:report_date]
      # Get date if given from form
      @date = Date.new(params[:report_date][:year].to_i, params[:report_date][:month].to_i, params[:report_date][:day].to_i)
    else
      # If no date is given, use today
      @date = Date.today
    end

    # Create a relation containing all elements for the report
    case params[:type]
      when "daily"
        logs = current_user.daily_log.where(log_date: @date)
      when "mtd"
        logs = current_user.daily_log.where(log_date: @date.beginning_of_month .. @date)
      when "monthly"
        logs = current_user.daily_log.where(log_date: (@date - 1.month) .. @date)
      else
        # If nothing is supplied, provide the daily report
        logs = current_user.daily_log.where(log_date: @date)
    end

    @min = logs.first.values.first rescue 0
    @max = logs.first.values.first rescue 0
    sum = 0
    count = 0
    logs.each do |log|
      @min = log.values.min if log.values.min < @min
      @max = log.values.max if log.values.max > @max
      sum += log.values.sum
      count += log.values.count
    end
    @avg = sum.fdiv(count).ceil rescue 0

  end

  def new
    @value = 0
  end

  def create
    value = Integer(params[:value]) rescue nil
    # Set date based on how it's presented to the controller
    if params[:date]
      date = params[:date]
    elsif params[:item_date]
      date = Date.new(params[:item_date][:year].to_i, params[:item_date][:month].to_i, params[:item_date][:day].to_i)
    end

    # Create entry if we have a value to try using
    if value
      daily_log = current_user.daily_log.find_by(log_date: date)
      if daily_log
        daily_log.add(value)
      else
        daily_log = current_user.daily_log.new(log_date: date, values: [value])
      end
      if !daily_log.save
        flash[:danger] = daily_log.errors.full_messages.to_sentence.downcase
        render :new
      else
        redirect_to daily_log_report_path
      end
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_log_helper.rb
module DailyLogHelper
end

app/views/daily_log/new.html.erb
<div class="row">
  <h1>Reading Input</h1>
</div>
<div class="row">
  <%= form_tag("/daily_log", method: "post") do %>
    <%= label_tag(:item_date, "Date: ") %>
    <%= select_date Date.today, prefix: :item_date %>
    <%= label_tag(:value, "Value:", class: "second-label") %>
    <%= text_field_tag(:value) %>
    <%= submit_tag("Submit") %>
  <% end %>
</div>

app/views/daily_log/report.html.erb
<div class="row">
  <h1>Reports</h1>
</div>
<div class="row report-selections">
  <%= form_tag("/daily_log/report", method: "get") do %>
    <%= label_tag(:report_date, "Date:") %>
    <%= select_date @date, prefix: :report_date %>
    <%= label_tag(:type, "Type:", class: "second-label") %>
    <%= select_tag(:type, options_for_select([["Daily", "daily"], ["Month to Date", "mtd"], ["Monthly", "monthly"]], params[:type])) %>
    <%= submit_tag("Get Report") %>
    <%= link_to "New Entry", new_daily_log_path, :class => "add-item" %>
  <% end %>
</div>
<div class="row results">
  <div class="col-sm-4">
    Minimum: <%= @min %>
  </div>
  <div class="col-sm-4">
    Maximum: <%= @max %>
  </div>
  <div class="col-sm-4">
    Average: <%= @avg %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sweety</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main-container" class="container">
      <div class="row">
        <nav class="navbar navbar-default">
          <div class="container">
            <div class="navbar-header">
              <%= link_to "Sweety", daily_log_report_path, class: "navbar-brand" %>
            </div>
          </div>
        </nav>
      </div>
      <div class="row">
        <% flash.each do |key, value| %>
          <%= content_tag :div, value, class: "alert alert-#{key}" %>
        <% end %>
      </div>
      <div id="main-content" class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>